// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpdPT0xdwRKnLeJk5awDFKF5KqcSUWdRY',
    appId: '1:188767015495:web:ef0d3436f49d1bcea19762',
    messagingSenderId: '188767015495',
    projectId: 'pantry-ai-59e44',
    authDomain: 'pantry-ai-59e44.firebaseapp.com',
    storageBucket: 'pantry-ai-59e44.firebasestorage.app',
    measurementId: 'G-KMPEXB53GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6TNdgorJqjI_zAIN1PzaFJH9ip3uNU80',
    appId: '1:188767015495:android:77be0d472d43177aa19762',
    messagingSenderId: '188767015495',
    projectId: 'pantry-ai-59e44',
    storageBucket: 'pantry-ai-59e44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rDdqySlKFXDM4DJTEVdU9IlMrT8gqEo',
    appId: '1:188767015495:ios:ea3c6c85b2db5e75a19762',
    messagingSenderId: '188767015495',
    projectId: 'pantry-ai-59e44',
    storageBucket: 'pantry-ai-59e44.firebasestorage.app',
    iosClientId: '188767015495-q095321d76jt6eb58sjulksg23k14c2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantryAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1rDdqySlKFXDM4DJTEVdU9IlMrT8gqEo',
    appId: '1:188767015495:ios:ea3c6c85b2db5e75a19762',
    messagingSenderId: '188767015495',
    projectId: 'pantry-ai-59e44',
    storageBucket: 'pantry-ai-59e44.firebasestorage.app',
    iosClientId: '188767015495-q095321d76jt6eb58sjulksg23k14c2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantryAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpdPT0xdwRKnLeJk5awDFKF5KqcSUWdRY',
    appId: '1:188767015495:web:f9cb748c611234a0a19762',
    messagingSenderId: '188767015495',
    projectId: 'pantry-ai-59e44',
    authDomain: 'pantry-ai-59e44.firebaseapp.com',
    storageBucket: 'pantry-ai-59e44.firebasestorage.app',
    measurementId: 'G-QZDQB9X6T9',
  );
}
